# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Miku.PWM
tagline:             Rem fanclub
description:         Fang makes stuff.
home:				 http://pyramidian.github.io
url:                 http://pyramidian.github.io/Webdev-test-3.0
baseurl:             /Webdev-test-3.0/
nodeurl:             /Webdev-test-3.0/about/
paginate:            5

# About/contact
author:
  name:              Fangzhou Yu
  url:              ''
  email:             fangzhou.yu@stonybrook.edu

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
